<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
<meta name="theme-color" content="#222">
<meta name="generator" content="Hexo 5.2.0">
  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">



<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/animate.css@3.1.1/animate.min.css">

<script class="hexo-configurations">
    var NexT = window.NexT || {};
    var CONFIG = {"hostname":"zhangshizuan.github.io","root":"/","scheme":"Mist","version":"8.0.0","exturl":false,"sidebar":{"position":"left","display":"post","padding":18,"offset":12},"copycode":false,"bookmark":{"enable":false,"color":"#222","save":"auto"},"fancybox":false,"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"motion":{"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"Searching...","empty":"We didn't find any results for the search: ${query}","hits_time":"${hits} results found in ${time} ms","hits":"${hits} results found"}};
  </script>

  <meta name="description" content="初识try-catch什么是异常处理异常是在程序中导致程序中断运行的一种指令流。例如，现在有如下的操作代码： 12345678910111213141516public class ExceptionDemo01&amp;#123;    public static void main(String argsp[])&amp;#123;        int i &#x3D; 10 ;        int j &#x3D; 0 ;">
<meta property="og:type" content="article">
<meta property="og:title" content="try-catch详解">
<meta property="og:url" content="https://zhangshizuan.github.io/2020/09/26/try-catch%E8%AF%A6%E8%A7%A3/index.html">
<meta property="og:site_name" content="Hexo">
<meta property="og:description" content="初识try-catch什么是异常处理异常是在程序中导致程序中断运行的一种指令流。例如，现在有如下的操作代码： 12345678910111213141516public class ExceptionDemo01&amp;#123;    public static void main(String argsp[])&amp;#123;        int i &#x3D; 10 ;        int j &#x3D; 0 ;">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="e:/JAVA培训/博客/blog/AmbitionZ/source/_posts">
<meta property="article:published_time" content="2020-09-26T15:42:17.000Z">
<meta property="article:modified_time" content="2020-09-28T10:49:37.909Z">
<meta property="article:author" content="zhangshizuan">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="e:/JAVA培训/博客/blog/AmbitionZ/source/_posts">


<link rel="canonical" href="https://zhangshizuan.github.io/2020/09/26/try-catch%E8%AF%A6%E8%A7%A3/">


<script class="page-configurations">
  // https://hexo.io/docs/variables.html
  CONFIG.page = {
    sidebar: "",
    isHome : false,
    isPost : true,
    lang   : 'en'
  };
</script>

  <title>try-catch详解 | Hexo</title>
  






  <noscript>
  <style>
  body { margin-top: 2rem; }

  .use-motion .menu-item,
  .use-motion .sidebar,
  .use-motion .post-block,
  .use-motion .pagination,
  .use-motion .comments,
  .use-motion .post-header,
  .use-motion .post-body,
  .use-motion .collection-header {
    visibility: visible;
  }

  .use-motion .header,
  .use-motion .site-brand-container .toggle,
  .use-motion .footer { opacity: initial; }

  .use-motion .site-title,
  .use-motion .site-subtitle,
  .use-motion .custom-logo-image {
    opacity: initial;
    top: initial;
  }

  .use-motion .logo-line {
    transform: scaleX(1);
  }

  .search-pop-overlay, .sidebar-nav { display: none; }
  .sidebar-panel { display: block; }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage" class="use-motion">
  <div class="headband"></div>

  <main class="main">
    <header class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="Toggle navigation bar">
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <i class="logo-line"></i>
      <h1 class="site-title">Hexo</h1>
      <i class="logo-line"></i>
    </a>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger">
    </div>
  </div>
</div>







</div>
        
  
  <div class="toggle sidebar-toggle">
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
  </div>

  <aside class="sidebar">

    <div class="sidebar-inner sidebar-nav-active sidebar-toc-active">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-toc">
          Table of Contents
        </li>
        <li class="sidebar-nav-overview">
          Overview
        </li>
      </ul>

      <!--noindex-->
      <section class="post-toc-wrap sidebar-panel">
          <div class="post-toc animated"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%88%9D%E8%AF%86try-catch"><span class="nav-number">1.</span> <span class="nav-text">初识try-catch</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#%E4%BB%80%E4%B9%88%E6%98%AF%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86"><span class="nav-number">1.1.</span> <span class="nav-text">什么是异常处理</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84"><span class="nav-number">1.2.</span> <span class="nav-text">异常体系结构</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#%E7%94%A8try-catch%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8"><span class="nav-number">1.3.</span> <span class="nav-text">用try-catch处理异常</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#try-catch%E8%A7%A3%E6%9E%90"><span class="nav-number">2.</span> <span class="nav-text">try-catch解析</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#try-catch%E7%9A%84%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B"><span class="nav-number">2.1.</span> <span class="nav-text">try+catch的处理流程</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#try"><span class="nav-number">2.2.</span> <span class="nav-text">try{}</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#catch"><span class="nav-number">2.3.</span> <span class="nav-text">catch({}</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally"><span class="nav-number">2.4.</span> <span class="nav-text">finally{}</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E7%9B%B8%E5%85%B3%E9%9D%A2%E8%AF%95%E9%A2%98"><span class="nav-number">3.</span> <span class="nav-text">相关面试题</span></a></li></ol></div>
      </section>
      <!--/noindex-->

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-author animated" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">zhangshizuan</p>
  <div class="site-description" itemprop="description"></div>
</div>
<div class="site-state-wrap animated">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
          <a href="/archives">
          <span class="site-state-item-count">11</span>
          <span class="site-state-item-name">posts</span>
        </a>
      </div>
  </nav>
</div>



      </section>
    </div>
  </aside>
  <div class="sidebar-dimmer"></div>


    </header>

    
  <div class="back-to-top">
    <i class="fa fa-arrow-up"></i>
    <span>0%</span>
  </div>

<noscript>
  <div class="noscript-warning">Theme NexT works best with JavaScript enabled</div>
</noscript>


    <div class="main-inner post posts-expand">
      

      

    
  
  
  <article itemscope itemtype="http://schema.org/Article" class="post-block" lang="en">
    <link itemprop="mainEntityOfPage" href="https://zhangshizuan.github.io/2020/09/26/try-catch%E8%AF%A6%E8%A7%A3/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="zhangshizuan">
      <meta itemprop="description" content="">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Hexo">
    </span>

    
    
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          try-catch详解
        </h1>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">Posted on</span>

      <time title="Created: 2020-09-26 23:42:17" itemprop="dateCreated datePublished" datetime="2020-09-26T23:42:17+08:00">2020-09-26</time>
    </span>
      <span class="post-meta-item">
        <span class="post-meta-item-icon">
          <i class="far fa-calendar-check"></i>
        </span>
        <span class="post-meta-item-text">Edited on</span>
        <time title="Modified: 2020-09-28 18:49:37" itemprop="dateModified" datetime="2020-09-28T18:49:37+08:00">2020-09-28</time>
      </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
        <h2 id="初识try-catch"><a href="#初识try-catch" class="headerlink" title="初识try-catch"></a>初识try-catch</h2><h3 id="什么是异常处理"><a href="#什么是异常处理" class="headerlink" title="什么是异常处理"></a>什么是异常处理</h3><p>异常是在程序中导致程序中断运行的一种指令流。<br>例如，现在有如下的操作代码：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo01</span></span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String argsp[])</span></span>&#123;</span><br><span class="line">        <span class="keyword">int</span> i = <span class="number">10</span> ;</span><br><span class="line">        <span class="keyword">int</span> j = <span class="number">0</span> ;</span><br><span class="line">        System.out.println(“============= 计算开始 =============”) ;</span><br><span class="line">        <span class="keyword">int</span> temp = i / j ; <span class="comment">// 进行除法运算</span></span><br><span class="line">        System.out.println(“temp = “ + temp) ;</span><br><span class="line">        System.out.println(“============= 计算结束 =============”) ;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line">运行结果：</span><br><span class="line"></span><br><span class="line">============= 计算开始 =============</span><br><span class="line">Exception in thread “main” java.lang.ArithmeticException: / by zero</span><br><span class="line">at ExceptionDemo01.main(ExceptionDemo01.java:<span class="number">6</span>)</span><br></pre></td></tr></table></figure>
<p>以上的代码在“int temp = i / j ;”位置处产生了异常，一旦产生异常之后，异常之后的语句将不再执行了，所以现<br>在的程序并没有正确的执行完毕之后就退出了。<br>那么，为了保证程序出现异常之后仍然可以正确的执行完毕，所以要采用异常的处理机制。</p>
<h3 id="异常体系结构"><a href="#异常体系结构" class="headerlink" title="异常体系结构"></a>异常体系结构</h3><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">异常指的是Exception ， Exception类， 在Java中存在一个父类Throwable（可能的抛出）</span><br><span class="line">Throwable存在两个子类：</span><br><span class="line">1.Error：表示的是错误，是JVM发出的错误操作,只能尽量避免，无法用代码处理。</span><br><span class="line">2.Exception：一般表示所有程序中的错误，所以一般在程序中将进行try…catch的处理。</span><br></pre></td></tr></table></figure>

<p><img src="E:/JAVA培训/博客/blog/AmbitionZ/source/_posts" alt="图片无"></p>
<h3 id="用try-catch处理异常"><a href="#用try-catch处理异常" class="headerlink" title="用try-catch处理异常"></a>用try-catch处理异常</h3><p>如果要想对异常进行处理，则必须采用标准的处理格式，处理格式语法如下：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>&#123;</span><br><span class="line">    <span class="comment">// 有可能发生异常的代码段</span></span><br><span class="line">&#125;<span class="keyword">catch</span>(异常类型<span class="number">1</span> 对象名<span class="number">1</span>)&#123;</span><br><span class="line">    <span class="comment">// 异常的处理操作</span></span><br><span class="line">&#125;<span class="keyword">catch</span>(异常类型<span class="number">2</span> 对象名<span class="number">2</span>)&#123;</span><br><span class="line">    <span class="comment">// 异常的处理操作</span></span><br><span class="line">&#125; ...</span><br><span class="line"><span class="keyword">finally</span>&#123;</span><br><span class="line">    <span class="comment">// 异常的统一出口</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="try-catch解析"><a href="#try-catch解析" class="headerlink" title="try-catch解析"></a>try-catch解析</h2><h3 id="try-catch的处理流程"><a href="#try-catch的处理流程" class="headerlink" title="try+catch的处理流程"></a>try+catch的处理流程</h3><ol>
<li>一旦产生异常，则系统会自动产生一个异常类的实例化对象。</li>
<li>那么，此时如果异常发生在try语句，则会自动找到匹配的catch语句执行，如果没有在try语句中，则会将异<br>常抛出.</li>
<li>所有的catch根据方法的参数匹配异常类的实例化对象，如果匹配成功，则表示由此catch进行处理。</li>
</ol>
<h3 id="try"><a href="#try" class="headerlink" title="try{}"></a>try{}</h3><p>try{}中放置那些在运行时可能会发生异常的代码，是异常处理程序的入口</p>
<h3 id="catch"><a href="#catch" class="headerlink" title="catch({}"></a>catch({}</h3><p>catch中是针对各种程序异常进行的处理办法。</p>
<ol>
<li>针对单个异常<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">catch</span>(异常类型 对象名)&#123;</span><br><span class="line">    <span class="comment">// 异常的处理操作</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></li>
<li>同时针对多种异常<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">catch</span>(异常类型<span class="number">1</span> |异常类型<span class="number">2</span> 对象名)&#123;</span><br><span class="line"><span class="comment">//表示此块用于处理异常类型1 和 异常类型2 的异常信息</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></li>
<li>针对全部的异常<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">catch</span>(Exception 对象名)&#123;</span><br><span class="line">    <span class="comment">// 异常的处理操作</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="finally"><a href="#finally" class="headerlink" title="finally{}"></a>finally{}</h3>在进行异常的处理之后，在异常的处理格式中还有一个finally语句，那么此语句将作为异常的统一出口，不管是否产生了异常，最终都要执行此段代码。<strong>除非内存消失，，否则finally一定执行</strong>。<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">finally</span>&#123;</span><br><span class="line">    <span class="comment">// 异常的统一出口</span></span><br><span class="line">&#125;s</span><br></pre></td></tr></table></figure>

</li>
</ol>
<h2 id="相关面试题"><a href="#相关面试题" class="headerlink" title="相关面试题"></a>相关面试题</h2><p><strong>1. try-catch-finally 中哪个部分可以省略？</strong><br>答： catch和finally可以省略其中一个 ， catch和finally不能同时省略<br>注意:格式上允许省略catch块, 但是发生异常时就不会捕获异常了,我们在开发中也不会这样去写代码.</p>
<p><strong>2. try-catch-finally 中，如果 catch 中 return 了，finally 还会执行吗？</strong><br>答：finally中的代码会执行<br>详解：<br><strong>执行流程：</strong><br>    1) 先计算返回值， 并将返回值存储起来， 等待返回<br>    2) 执行finally代码块<br>    3) 将之前存储的返回值，返回出去；<br><strong>需注意：</strong><br>    1) 返回值是在finally运算之前就确定了，并且缓存了，不管finally对该值做任何的改变，返回的值都不会改变<br>    2) finally代码中<strong>不建议包含return</strong>，因为程序会在上述的流程中提前退出，也就是说返回的值不是try或catch中的值<br>    3) 如果在try或catch中<strong>停止了JVM</strong>,则finally不会执行.例如停电- -, 或通过如下代码退出</p>
<pre><code>JVM:System.exit(0);</code></pre>

    </div>

    
    
    

    <footer class="post-footer">

        

          <div class="post-nav">
            <div class="post-nav-item">
                <a href="/2020/09/25/leetcode1-%E4%B8%A4%E6%95%B0%E4%B9%8B%E5%92%8C/" rel="prev" title="leetcode1 两数之和">
                  <i class="fa fa-chevron-left"></i> leetcode1 两数之和
                </a>
            </div>
            <div class="post-nav-item">
                <a href="/2020/09/29/markdownss%E5%AD%A6%E4%B9%A0/" rel="next" title="markdown学习">
                  markdown学习 <i class="fa fa-chevron-right"></i>
                </a>
            </div>
          </div>
    </footer>
  </article>
  
  
  



      

<script>
  window.addEventListener('tabs:register', () => {
    let { activeClass } = CONFIG.comments;
    if (CONFIG.comments.storage) {
      activeClass = localStorage.getItem('comments_active') || activeClass;
    }
    if (activeClass) {
      const activeTab = document.querySelector(`a[href="#comment-${activeClass}"]`);
      if (activeTab) {
        activeTab.click();
      }
    }
  });
  if (CONFIG.comments.storage) {
    window.addEventListener('tabs:click', event => {
      if (!event.target.matches('.tabs-comment .tab-content .tab-pane')) return;
      const commentClass = event.target.classList[1];
      localStorage.setItem('comments_active', commentClass);
    });
  }
</script>

    </div>
  </main>

  <footer class="footer">
    <div class="footer-inner">
      

      

<div class="copyright">
  
  &copy; 
  <span itemprop="copyrightYear">2021</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">zhangshizuan</span>
</div>
  <div class="powered-by">Powered by <a href="https://hexo.io/" class="theme-link" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/mist/" class="theme-link" rel="noopener" target="_blank">NexT.Mist</a>
  </div>

    </div>
  </footer>

  
  <script src="//cdn.jsdelivr.net/npm/animejs@3.2.0/lib/anime.min.js"></script>
<script src="/js/utils.js"></script><script src="/js/motion.js"></script><script src="/js/schemes/muse.js"></script><script src="/js/next-boot.js"></script>

  















  








  

  

</body>
</html>
